apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.metadata.namespace }}
{{- if .Values.configmapData }}
data:
{{-  range $configmapKey, $configmapValue := .Values.configmapData }}
  {{ $configmapKey }}: {{ toYaml $configmapValue | quote }}
{{- end }}
{{- end }}
